config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :users, only: :destroy

  resources :invitations do
    resources :users
  end
  resources :participants do
    resources :consumptions
    get 'manage', on: :member
  end

  resource :scoreboard

  get 'static_pages/impress'
  get 'static_pages/privacy'
  get 'static_pages/about'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="flex flex-col gap-2">
  <% if current_participant %>
    <p class="font-bold">
    Hallo <%= render(ParticipantDisplayName.new(current_participant)) %>, du nimmst am Gewinnspiel teil! 
    </p>
    <%= link_to 'Jetzt Bier scannen', participant_path(current_participant), class: primary_button_class %>
    <hr />
  <% end %>
  <%= mark do %>
    Hallo Leute, wir sind von der [Fleischerei Konrad Pfandl](https://www.fleischerei-pfandl.at/), Unterer [Platz 3, 9300 St.Veit](https://maps.app.goo.gl/HvCDXEWQETKKCpfL8).

    Wir betreiben am Wiesenmarkt von St.Veit, von **28.09. bis 07.10.**, eine kulinarische Hütte.
    
    Heuer erstmalig _NEU_ für euch. Für unsere geschätzten Bierliebhaber. Ein QR-Code Gewinnspiel.

    Das Gewinnspiel startet **Montag den 30.09.** und endet somit am **Freitag den 04.10.** bei Sperrstunde.
      
    Siegerehrung beginnt **Sonntag den 06.10** _pünktlich_ um **18 Uhr**. Preise werden nur ausgegeben mit richtigen QR-Code und persönlicher Anwesenheit.

    ## Ablauf
   
    * jedes Bier 0,5l muss bei Kellner oder Theke eingescannt werden mit eurer Registrierung
    * in der Hütte gibt es eine Leinwand, die besten 5, die am meisten Bier bestellt haben, werden auf der Wand angezeigt
    * Für die ersten 3 Plätze gibt es natürlich besondere Preise

    ….also mitmachen , Bier bestellen und Gewinnen

    ## Preise

    * 1. Platz: UHD 4K TV 75"
    * 2. Platz: Grillerei im Wert von 400€
    * 3. Platz: Jahresvorrat Villacher Bier
  <% end %>
  <hr />
  <% if current_user %>
    <p class="font-bold">
      Du bist     <%= render UserDisplayName.new(current_user) %>
      <%= link_to 'Logout', user_path(current_user), data: { turbo_method: :delete } %>
    </p>
    <div class="grid grid-cols-2">
      <%= link_to 'Scoreboard', scoreboard_path, class: alternative_button_class %>
      <%= link_to 'Teilnehmer-Liste', participants_path, class: alternative_button_class  %>
      <%= link_to 'Benutzerverwaltung', invitations_path, class: alternative_button_class  if current_user.admin? %>
      <%= link_to 'Teilnehmer-Registration', new_participant_path, class: alternative_button_class %> 
      <%= link_to 'Teilnehmer-Registration (QR Code)', new_participant_path(format: 'png'), class: alternative_button_class  %>
    </div>
  <% else %>
    <%= link_to 'Jetzt mitmachen', new_participant_path, class: primary_button_class %>
  <% end %>
  <%= mark do %>
    ## Hilfe

    ### Sicherheit

    * Grundsatz: Hinter dem QR-Code versteckt sich ein einfacher Link. **Jeder kann QR-Codes generieren.** Ein potentieller Angreifer könnte die Gewinnspiel-App optisch nachbauen. ([Phishing](https://de.wikipedia.org/wiki/Phishing))
    * Grundsatz: Die App wird **nie** nach einer Username+Passwort-Kombination (oder sonstigen personenbezogenen Daten) fragen. Kannst du die 'Bier tracken'-Seite nach einem Scan nicht erreichen, dann scanne nochmal den Bar-Einladungs-QR-Code an der Bar um dich zu authentifizieren und scanne nochmal den QR-Code des Teilnehmers.
    * Die Einladungs-QR-Codes dürfen nur für Mitarbeiter erreichbar sein. Sollten Zweifel auftreten dass jemand anders Zugriff hatte, muss dieser Link in der [Benutzerverwaltung](<%= invitations_path %>) (nur mit Administrator-Zugang) deaktiviert werden.
    * Nach jedem Scan einen kurzen Blick in die Browser-Adressleiste werfen und vergleichen: <%= root_url %>

    ### Gewinnspiel auflösen

    * Scoreboard aufrufen
    * Spieler+Emoji ausrufen
    * QR-Code des Spielers scannen um die 'Bier tracken'-Seite aufzurufen
    * **Browser-Adressleiste kontrollieren**: <%= root_url %>
    * Spielername **UND** Emoji vergleichen; nur gemeinsam kann mit Sicherheit festgestellt werden ob es sich um die Richtige Person handelt
    * Preis ausgeben
  <% end if current_user %>
</div>