config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :users, only: :destroy

  resources :invitations do
    resources :users
  end
  resources :participants do
    resources :consumptions
    get 'manage', on: :member
  end

  resource :scoreboard

  get 'static_pages/impress'
  get 'static_pages/privacy'
  get 'static_pages/about'
end

app/models/participant.rb
class Participant < ApplicationRecord
  validates :name, presence: true

  has_many :consumptions

  scope :newest_first, -> { order(created_at: :desc) }
  scope :search_by_name, ->(name) { where('name like ?', "%#{sanitize_sql_like(name)}%") }

  def activated?
    !deactivated?
  end

  def emoji_id
    list = []
    remaining = id

    until remaining <= 0
      remaining, index = remaining.divmod(Opentrink::Emoji.alphabet.length)
      list.push(Opentrink::Emoji.alphabet[index])
    end

    list.join('')
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :require_bar, except: %i[new create show]

  def index
    @participants = Participant.newest_first

    @filters = ParticipantFiltersForm.new(
      params.fetch(:participant_filters_form, {}).permit(:q)
    )
    @participants = @participants.search_by_name(@filters.q) if @filters.q
  end

  def show
    @participant = Participant.find_by!(id: params[:id])

    raise 'not allowed' unless @participant.id == current_participant&.id
  end

  def manage
    @participant = Participant.find_by!(id: params[:id])
  end

  def new
    @participant = Participant.new

    respond_to do |format|
      format.html
      format.png do
        image_stream = RQRCode::QRCode.new(new_participant_url)
                                      .as_png(size: 500)
                                      .to_datastream

        send_data image_stream,
                  type: 'image/png',
                  disposition: 'inline'
      end
    end
  end

  def update
    participant = Participant.find_by!(id: params[:id])

    ScoreboardNotifier.new.notify! do
      participant.update!(params.require(:participant).permit(:deactivated))
    end

    redirect_to action: :manage
  end

  def create
    @participant = Participant.new(params.require(:participant).permit(:name))

    if @participant.save
      self.current_participant = @participant
      redirect_to action: :show, id: @participant.id
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/participant_helper.rb
module ParticipantHelper
end

app/views/participants/index.html.erb
<div class="grid gap-3">
  <h1 class="text-3xl font-bold">Teilnehmer</h1>
  <p>
    Anzahl: <%= @participants.count %>
  </p>
  <%= app_form_with(model: @filters, method: :get, url: participants_path, data: { turbo: false }) do |f| %>
    <div class="flex gap-2 items-center">
      <%= f.text_field(:q) %>
      <%= f.submit("Search") %>
    </div>
  <% end %>
  <ul class="flex flex-col gap-5 divide-y divide-gray-200">
    <% @participants.each do |participant| %>
      <li class="py-3 flex flex-col">
        <%= link_to manage_participant_path(participant.id) do %>
          <%= render ParticipantDisplayName.new(participant) %>
        <% end %>
        <span>Registriert: <%= l participant.created_at, format: :short %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/participants/manage.html.erb
<div class="grid gap-8 space-y space-y-3">
  <div class="flex flex-row justify-between align-center">
    <h1 class="text-3xl font-bold">Teilnehmer</h1>
      <%= link_to 'Konsum', participant_consumptions_path(@participant), class: alternative_button_class %>
  </div>

  <div class="flex flex-col gap-3">
    <span><%= render ParticipantDisplayName.new(@participant) %></span>
    <span>Registriert: <%= l @participant.created_at, format: :short %></span>
    <span>Zuletzt geändert: <%= l @participant.updated_at, format: :short %></span>
  </div>

  <% if @participant.deactivated? %>
    <div class="bg-red-100 p-3 flex flex-col gap-3">
      <span>Dieser Teilnehmer wurde <strong>deaktiviert</strong>. Somit taucht er nicht mehr am Scoreboard auf und kann keine neuen Konsumationen erstellen lassen.</span>
      <%= link_to "Aktivieren",
        participant_path(@participant.id,
                         participant: { deactivated: false }), 
        class: primary_button_class,
        data: { turbo_method: 'put', turbo_track: 'reload' } %>
    </div>
  <% else %>
    <div class="bg-orange-100 p-3 flex flex-col gap-3">
      <span>Teilnehmer deaktivieren um ihn vom Scoreboard auszublenden und davor zu hindern neue Konsumationen erstellen zu lassen. (Teilnehmer wird auf seiner 'Jetzt Bier scannen'-Page über diesen Status informiert.)</span>
      <%= link_to "Deaktivieren",
        participant_path(@participant.id,
                         participant: { deactivated: true }), 
        class: primary_button_class,
        data: { turbo_method: 'put', turbo_track: 'reload' } %>
    </div>
  <% end %>
</div>

app/views/participants/new.html.erb
<% if current_participant %>
  <div class="grid gap-2 mb-[100vh]">
    <p class="font-bold">
    Hallo <%= render(ParticipantDisplayName.new(current_participant)) %>, du nimmst am Gewinnspiel teil! 
    </p>
    <%= link_to 'Jetzt Bier scannen', participant_path(current_participant), class: primary_button_class %>
  </div>
<% end %>
<%= app_form_with model: @participant, data: { turbo: false } do |form| %>
  <div class="grid gap-6">
    <%= mark do %>
      Hallo Leute, wir sind von der [Fleischerei Konrad Pfandl](https://www.fleischerei-pfandl.at/), Unterer [Platz 3, 9300 St.Veit](https://maps.app.goo.gl/HvCDXEWQETKKCpfL8).

      Wir betreiben am Wiesenmarkt von St.Veit, von **28.09. bis 07.10.**, eine kulinarische Hütte.
      
      Heuer erstmalig _NEU_ für euch. Für unsere geschätzten Bierliebhaber. Ein QR-Code Gewinnspiel.

      Das Gewinnspiel startet **Montag den 30.09.** und endet somit am **Freitag den 04.10.** bei Sperrstunde.
        
      Siegerehrung beginnt **Sonntag den 06.10** _pünktlich_ um **18 Uhr**. Preise werden nur ausgegeben mit richtigen QR-Code und persönlicher Anwesenheit.

      ## Ablauf
     
      * du registrierst dich hier mit deinem Smartphone und einem Namen deiner Wahl, welchen wir auf der Leinwand zeigen (_bitte beachte dass der Name der Etikette entspricht, ansonsten sind wir gezwungen dich vom Gewinnspiel zu entfernen_)
      * jedes Bier 0,5l muss bei Kellner oder Theke eingescannt werden mit eurer Registrierung (<%= link_to 'Gewinnspiel', root_path %> -> 'Jetzt Bier scannen')
      * in der Hütte gibt es eine Leinwand, die besten 5, die am meisten Bier bestellt haben, werden auf der Wand angezeigt
      * Für die ersten 3 Plätze gibt es natürlich besondere Preise

      ….also mitmachen , Bier bestellen und Gewinnen

      ## Preise

      * 1. Platz: UHD 4K TV 75"
      * 2. Platz: Grillerei im Wert von 400€
      * 3. Platz: Jahresvorrat Villacher Bier
    <% end %>
    <% if current_participant %>
      <p class="p-4 mb-4 text-lg text-red-800 rounded-lg bg-red-50">
        Achtung! Du nimmst aktuell schon als '<%= link_to current_participant.name, participant_path(current_participant) %>' am Gewinnspiel teil. Wenn du dich nochmals registrierst, verlierst du deinen Platz!
      </p>
    <% end %>
    <%= form.input_group do %>
      <%= form.label :name, "Teilnehmer-Name" %>
      <%= form.text_field :name %>
      <%= form.error_texts :name %>
    <% end %>
    <% if current_participant %>
      <p class="p-4 mb-4 text-lg text-red-800 rounded-lg bg-red-50">
        Achtung! Du nimmst aktuell schon als '<%= link_to current_participant.name, participant_path(current_participant) %>' am Gewinnspiel teil. Wenn du dich nochmals registrierst, verlierst du deinen Platz!
      </p>
    <% end %>
    <%= form.submit "Teilnehmen!" %>
    <%= mark do %>
      ## Datenschutz

      Wir speichern ausschließlich den von dir ausgewählten Namen, sowie den Zeitpunkt und Menge der von dir bestellten Biere (sofern du deinen Registrations-QR-Code vorzeigst). Sofern du unter den besten 5 bist, zeigen wir deinen Namen und die Anzahl der von dir bestellten Biere öffentlich auf einer Leinwand. Es steht dir frei einen beliebigen Namen zu wählen (dein voller Vor- und Nachname ist somit nicht für die Teilnahme notwendig). Die gesammelten Daten werden unmittelbar nach der Siegerehrung gelöscht. <%= link_to 'Mehr Informationen', static_pages_privacy_path %>
    <% end %>
  </div>
<% end %>

app/views/participants/show.html.erb
<div 
  data-controller="refresh" 
  data-refresh-interval-value="<%= 5.minutes.to_i %>"
></div>

<% if @participant.activated? %>
  <div class="flex flex-col gap-2">
    <p>Du nimmst jetzt teil, <%= render(ParticipantDisplayName.new(@participant)) %></p>
    <p>Lass diesen QR-Code <strong>bei einem Kellner oder an der Theke einscannen</strong> damit deine 🍺 Bier-Bestellung gezählt werden kann.</p>
  </div>

  <div class="grid mt-6">
    <%= RQRCode::QRCode.new(new_participant_consumption_url(@participant.signed_id(expires_in: 30.minutes))).as_svg(viewbox: true).html_safe %>
  </div>
<% else %>
  <p class="bg-red-100 p-3">Lieber <%= render(ParticipantDisplayName.new(@participant)) %>, wir müssen dir leider mitteilen dass du deaktiviert wurdest. Das heißt dass du keine weiteren Bestellungen scannen lassen kannst und auch am Scoreboard nicht angezeigt wirst. Bitte sprich einen unserer Kellner an um die Situation aufzuklären. Du kannst dich jedoch jederzeit <%= link_to 'neu-registrieren', new_participant_path %>.</p>
<% end %>