config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :users, only: :destroy

  resources :invitations do
    resources :users
  end
  resources :participants do
    resources :consumptions
    get 'manage', on: :member
  end

  resource :scoreboard

  get 'static_pages/impress'
  get 'static_pages/privacy'
  get 'static_pages/about'
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :created_by, class_name: 'User', optional: true
  has_many :users

  before_create :set_id

  scope :newest_first, -> { order(created_at: :desc) }
  scope :activated, -> { where(deactivated: false) }

  enum :role, { bar: 'bar', admin: 'admin' }

  def activated?
    !deactivated?
  end

  private

  def set_id
    self.id = SecureRandom.uuid if self.id.blank?
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :require_admin

  def index
    @invitations = Invitation.all.newest_first
  end

  def create
    @invitation = Invitation.new(params.require(:invitation).permit(:role))

    @invitation.save!
    redirect_to action: :index
  end

  def update
    invitation.update!(params.require(:invitation).permit(:deactivated))
    redirect_to action: :index
  end

  private

  def invitation
    @invitation ||= Invitation.find_by(id: params[:id])
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/index.html.erb
<div class="grid gap-8 space-y space-y-3">
  <div class="flex flex-row justify-between align-center">
    <h1 class="text-3xl font-bold">Einladungen</h1>
    <%= link_to '+ Bar', invitations_path(invitation: { role: :bar }),
      data: { turbo_method: :post },
      class: alternative_button_class %>
  </div>
  
  <turbo-frame id="invitations">
    <ul class="flex flex-col gap-5 divide-y divide-gray-200">
      <% @invitations.each_with_index do |invitation, index| %>
        <li class="py-3 flex flex-col gap-2">
          <span class="<%= clsx('uppercase', 'font-bold', 'line-through' => invitation.deactivated?) %>">
            <%= "Admin-Link" if invitation.admin? %>
            <%= "Bar-Link" if invitation.bar? %>
            #<%= @invitations.length - (index + 1) %> 
          </span>
          <div class="grid grid-cols-2">
            <%= link_to 'QR Code', new_invitation_user_url(invitation, format: 'png') , class: alternative_button_class if invitation.activated? %> 
            <% if invitation.activated? %>
              <%= link_to "Deaktivieren", invitation_path(invitation.id, invitation: { deactivated: true }), data: { turbo_method: 'put' }, class: danger_button_class %>
            <% else %>
              <%= link_to "Aktivieren", invitation_path(invitation.id, invitation: { deactivated: false }), data: { turbo_method: 'put' }, class: alternative_button_class %>
            <% end %>
          </div>
          <ul class="border-x-4 border-zinc-500 px-4 flex flex-col divide-y divide-gray-200 space-y space-y-1">
            <% invitation.users.newest_first.each do |user| %>
              <li 
                class="data-[deactivated=true]:bg-gray-200 py-4 px-2 flex flex-col gap-2"
                data-deactivated="<%= "true" if user.deactivated? %>">
                <span>#<%= user.id %> <%= render UserDisplayName.new(user, role_label: false) %></span>

                <span class="flex flex-col items-end">
                  <% if user.activated? %>
                    <%= link_to "Deaktivieren", invitation_user_path(invitation.id, user.id, user: { deactivated: true }), 
                      data: { turbo_method: 'put', turbo_track: 'reload', turbo_confirm: "Bist du dir sicher? User können nicht re-aktiviert werden." }, class: danger_button_class %>
                  <% else %>
                    [deaktiviert]
                  <% end %>
                </span>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </turbo-frame>
</div>