config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :users, only: :destroy

  resources :invitations do
    resources :users
  end
  resources :participants do
    resources :consumptions
    get 'manage', on: :member
  end

  resource :scoreboard

  get 'static_pages/impress'
  get 'static_pages/privacy'
  get 'static_pages/about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pfandl Bierolympiade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'es-module-shims.js', async: true, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="">
    <header class="container mx-auto px-5 pt-5 flex flex-col bg-[#ad9b63]">
      <h1 class="flex font-extrabold leading-none">
        <%= link_to root_path, class: 'unstyled inline-flex flex-col gap-3.5' do %>
          <span class="uppercase text-white text-6xl tracking-tight">Pfandl</span>
          <span class="text-zinc-900 text-4xl tracking-widest">Bierolympiade</span>
        <% end %>
      </h1>
      <div class="-mx-5 px-5 py-2 mt-5 bg-zinc-900 text-gray-200">
        <span>Unterer Platz 3</span>
        <span>9300 St. Veit an der Glan</span>
      </div>
    </header>
    <main class="container mx-auto p-5 flex flex-col">
      <%= yield %>
    </main>
    <footer class="shadow bg-gray-200">
      <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
        <span class="text-sm text-gray-500 sm:text-center">© 2024 <a href="https://fleischerei-pfandl.at/" class="hover:underline">Fleischerei Pfandl</a>
        </span>
        <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 sm:mt-0">
            <li>
              <%= link_to 'Über', static_pages_about_path, class: 'hover:underline me-4 md:me-6' %>
            </li>
            <li>
              <%= link_to 'Impressum', static_pages_impress_path, class: 'hover:underline me-4 md:me-6' %>
            </li>
            <li>
              <%= link_to 'Datenschutz', static_pages_privacy_path, class: 'hover:underline me-4 md:me-6' %>
            </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/presentation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pfandl Bierolympiade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'es-module-shims.js', async: true, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen">
    <%= yield %>
  </body>
</html>